//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempWebApp.DistanceMatrixService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistanceMatrixService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDistance", ReplyAction="http://tempuri.org/IService1/getDistanceResponse")]
        int getDistance(string city1, string city2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDistance", ReplyAction="http://tempuri.org/IService1/getDistanceResponse")]
        System.Threading.Tasks.Task<int> getDistanceAsync(string city1, string city2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTime", ReplyAction="http://tempuri.org/IService1/getTimeResponse")]
        string getTime(string city1, string city2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getTime", ReplyAction="http://tempuri.org/IService1/getTimeResponse")]
        System.Threading.Tasks.Task<string> getTimeAsync(string city1, string city2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TempWebApp.DistanceMatrixService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TempWebApp.DistanceMatrixService.IService1>, TempWebApp.DistanceMatrixService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getDistance(string city1, string city2) {
            return base.Channel.getDistance(city1, city2);
        }
        
        public System.Threading.Tasks.Task<int> getDistanceAsync(string city1, string city2) {
            return base.Channel.getDistanceAsync(city1, city2);
        }
        
        public string getTime(string city1, string city2) {
            return base.Channel.getTime(city1, city2);
        }
        
        public System.Threading.Tasks.Task<string> getTimeAsync(string city1, string city2) {
            return base.Channel.getTimeAsync(city1, city2);
        }
    }
}
