//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempWebApp.PlacesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaceResults", Namespace="http://schemas.datacontract.org/2004/07/placesService")]
    [System.SerializableAttribute()]
    public partial class PlaceResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PetrolPumpsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RestaurantsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PetrolPumps {
            get {
                return this.PetrolPumpsField;
            }
            set {
                if ((object.ReferenceEquals(this.PetrolPumpsField, value) != true)) {
                    this.PetrolPumpsField = value;
                    this.RaisePropertyChanged("PetrolPumps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Restaurants {
            get {
                return this.RestaurantsField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantsField, value) != true)) {
                    this.RestaurantsField = value;
                    this.RaisePropertyChanged("Restaurants");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlacesService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchNearby", ReplyAction="http://tempuri.org/IService1/SearchNearbyResponse")]
        TempWebApp.PlacesService.PlaceResults SearchNearby(string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchNearby", ReplyAction="http://tempuri.org/IService1/SearchNearbyResponse")]
        System.Threading.Tasks.Task<TempWebApp.PlacesService.PlaceResults> SearchNearbyAsync(string destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TempWebApp.PlacesService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TempWebApp.PlacesService.IService1>, TempWebApp.PlacesService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TempWebApp.PlacesService.PlaceResults SearchNearby(string destination) {
            return base.Channel.SearchNearby(destination);
        }
        
        public System.Threading.Tasks.Task<TempWebApp.PlacesService.PlaceResults> SearchNearbyAsync(string destination) {
            return base.Channel.SearchNearbyAsync(destination);
        }
    }
}
