//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempWebApp.WeatherService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherService.IWeatherService")]
    public interface IWeatherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetGoogleWeather", ReplyAction="http://tempuri.org/IWeatherService/GetGoogleWeatherResponse")]
        string GetGoogleWeather(string location1, string location2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetGoogleWeather", ReplyAction="http://tempuri.org/IWeatherService/GetGoogleWeatherResponse")]
        System.Threading.Tasks.Task<string> GetGoogleWeatherAsync(string location1, string location2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetWeatherData", ReplyAction="http://tempuri.org/IWeatherService/GetWeatherDataResponse")]
        string GetWeatherData(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherService/GetWeatherData", ReplyAction="http://tempuri.org/IWeatherService/GetWeatherDataResponse")]
        System.Threading.Tasks.Task<string> GetWeatherDataAsync(string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeatherServiceChannel : TempWebApp.WeatherService.IWeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceClient : System.ServiceModel.ClientBase<TempWebApp.WeatherService.IWeatherService>, TempWebApp.WeatherService.IWeatherService {
        
        public WeatherServiceClient() {
        }
        
        public WeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGoogleWeather(string location1, string location2) {
            return base.Channel.GetGoogleWeather(location1, location2);
        }
        
        public System.Threading.Tasks.Task<string> GetGoogleWeatherAsync(string location1, string location2) {
            return base.Channel.GetGoogleWeatherAsync(location1, location2);
        }
        
        public string GetWeatherData(string location) {
            return base.Channel.GetWeatherData(location);
        }
        
        public System.Threading.Tasks.Task<string> GetWeatherDataAsync(string location) {
            return base.Channel.GetWeatherDataAsync(location);
        }
    }
}
